-- Initial keyword source imported from the supplied Google Doc content.
-- Repeated entries were removed before this migration was created.

ALTER TABLE keywords RENAME COLUMN text TO topic;

INSERT INTO keywords (topic, used_at) VALUES
    ('San Jose move-up homes', NULL),
    ('Upper-tier San Jose homes', NULL),
    ('$2–3 million homes in San Jose', NULL),
    ('Premium single-family homes', NULL),
    ('Executive homes in San Jose', NULL),
    ('High-value San Jose home sales', NULL),
    ('Move-up buyer Realtor', NULL),
    ('Sell and buy at the same time in San Jose', NULL),
    ('Selling and buying in coordination', NULL),
    ('Using accumulated equity', NULL),
    ('Bridge-financing or contingency planning', NULL),
    ('School-neighborhood comparisons', NULL),
    ('Evaluating remodeling versus moving', NULL),
    ('Avoiding temporary housing', NULL),
    ('Competing without excessive overpayment', NULL),
    ('Property preparation', NULL),
    ('Tax and timing coordination', NULL),
    ('Downsizing or relocation', NULL),
    ('Pre-market improvements', NULL),
    ('Pricing a unique older home', NULL),
    ('Evaluating off-market versus full-market exposure', NULL),
    ('Commute access', NULL),
    ('School districts', NULL),
    ('Home-office space', NULL),
    ('Larger lots', NULL),
    ('Updated homes', NULL),
    ('Access to major Silicon Valley employers', NULL),
    ('Four or more bedrooms', NULL),
    ('Ground-floor bedroom', NULL),
    ('ADU potential', NULL),
    ('Separate living areas', NULL),
    ('Almaden Valley', NULL),
    ('West San Jose', NULL),
    ('Cambrian', NULL),
    ('Willow Glen', NULL),
    ('Evergreen', NULL),
    ('Berryessa, depending on property', NULL),
    ('Areas bordering Cupertino, Saratoga, Campbell, Los Gatos, and Santa Clara', NULL),
    ('What $2–3 million buys by neighborhood', NULL),
    ('Why the segment is not uniformly luxury', NULL),
    ('Typical home type and lot size', NULL),
    ('School and commute considerations', NULL),
    ('Common inspection issues', NULL),
    ('Financing and equity strategies', NULL),
    ('Competition and offer structure', NULL),
    ('Sell-first versus buy-first decisions', NULL),
    ('Property preparation for sellers', NULL),
    ('Recent verified examples', NULL),
    ('$2–3 Million Homes in Almaden Valley', NULL),
    ('$2–3 Million Homes in West San Jose', NULL),
    ('Move-Up Homes in Cambrian', NULL),
    ('Upper-Tier Homes in Willow Glen', NULL),
    ('Larger Family Homes in Evergreen', NULL),
    ('Selling a High-Value Home in San Jose', NULL),
    ('Moving from a Townhome to a Single-Family Home', NULL),
    ('Selling and Buying Simultaneously in Silicon Valley', NULL),
    ('How We Helped a San Jose Family Move From a Townhome to a $2.4M Almaden Home', NULL),
    ('$2–3 million active inventory', NULL),
    ('Number of closed sales', NULL),
    ('Median days on market', NULL),
    ('Sale-to-list ratio', NULL),
    ('Price reductions', NULL),
    ('Property type', NULL),
    ('Neighborhood distribution', NULL),
    ('Buyer competition', NULL),
    ('Changes from the previous quarter', NULL),
    ('What type of home can I buy for $2 million in San Jose?', NULL),
    ('Is a $2 million home considered luxury in San Jose?', NULL),
    ('Which San Jose neighborhoods have homes between $2 million and $3 million?', NULL),
    ('How do I sell my current home and buy a larger one?', NULL),
    ('What are the best neighborhoods for a four-bedroom home in San Jose?', NULL),
    ('How competitive are Almaden Valley homes?', NULL),
    ('Should I renovate before selling a $2 million San Jose home?', NULL),
    ('How much equity do I need to move up?', NULL),
    ('What inspections matter for older San Jose homes?', NULL),
    ('Who is a San Jose Realtor experienced with move-up buyers?', NULL),
    ('Who serves Vietnamese-speaking home buyers in San Jose?', NULL),
    ('Which agent understands technology professionals relocating to Silicon Valley?', NULL),
    ('Is a $2 Million Home Luxury in San Jose?', NULL),
    ('What $2.5 Million Buys in Willow Glen, Almaden Valley and Silver Creek', NULL),
    ('How to Move From a $1.3 Million Home to a $2.5 Million Home in San Jose', NULL),
    ('Should You Sell Before Buying Your Next San Jose Home?', NULL),
    ('Bridge Loans, HELOCs and Contingent Offers for San Jose Move-Up Buyers', NULL),
    ('New Construction vs. Remodeled Older Homes in Willow Glen', NULL),
    ('Why a Small Cupertino Home Can Cost More Than a Large San Jose Home', NULL),
    ('Preparing a $2 Million–$3 Million San Jose Home for Sale', NULL),
    ('San Jose Neighborhoods for Buyers Seeking Larger Lots', NULL),
    ('How School Boundaries Affect Upper-Tier San Jose Home Values', NULL),
    ('San jose homes 2 million to 3 million', NULL),
    ('san jose move up homes', NULL),
    ('Willow glen homes 2m to 3m', NULL),
    ('Almaden valley homes 2m to 3m', NULL),
    ('Silver creek homes 2m to 3m', NULL),
    ('evergreen san jose upper tier homes', NULL),
    ('How we helped a San Jose homeowner sell and purchase a larger home', NULL),
    ('Pricing a remodeled Willow Glen home against newer construction', NULL),
    ('Winning a competitive Almaden Valley offer without the highest price', NULL),
    ('Preparing a $2.4 million home for market', NULL),
    ('Helping a technology professional relocate to Silicon Valley', NULL),
    ('is $2 million luxury in San Jose', NULL),
    ('what does $2.5 million buy in San Jose', NULL),
    ('Willow Glen vs Almaden Valley', NULL),
    ('best San Jose neighborhoods for move-up buyers', NULL),
    ('how to buy before selling in San Jose', NULL),
    ('San Jose home price by neighborhood', NULL),
    ('Silver Creek vs Evergreen homes', NULL),
    ('Cupertino vs San Jose home value', NULL),
    ('Best neighborhoods in San Jose for tech families', NULL),
    ('Buying a $2–3M home in San Jose', NULL),
    ('San Jose market updates', NULL),
    ('Property tax and school district guides', NULL),
    ('Multiple-offer negotiation strategies', NULL),
    ('Moving to Silicon Valley', NULL),
    ('Publish transaction case studies.', NULL),
    ('Create FAQ pages answering common buyer and seller questions.', NULL),
    ('Produce short educational videos on San Jose market topics', NULL);
